spring:
  application:
    name: brewery-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pionas/brewery-config-repo
          clone-on-start: true
          search-paths: '{application}'
          default-label: 'main'
  security:
    user:
      name: config-server
      password: mkM5HxI2UpD51E5

server:
  port: 8888

logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework.web: DEBUG

eureka:
  username: netflix
  password: "{cipher}b0cb044ba3ebccd70a74dabc001df934d39851c11724918844a4d5e46c87a633"
  client:
    serviceUrl:
      defaultZone: http://${eureka.username}:${eureka.password}@localhost:8761/eureka

encrypt:
  key: MySUperSecretPassword