spring:
  application:
    name: brewery-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pionas/brewery-config-repo
          clone-on-start: true

server:
  port: 8888
