spring:
  application:
    name: brewery-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pionas/brewery-config-repo
          clone-on-start: true

server:
  port: 8888

logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework.web: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://netflix:eureka@localhost:8761/eureka
