spring:
  application:
    name: brewery-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pionas/brewery-config-repo
          clone-on-start: true
          search-paths: '{application}'
          default-label: 'main'

server:
  port: 8888

logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework.web: DEBUG

eureka:
  username: netflix
  password: "{cipher}AQArMkBS7/zgH087i4BlownXemkjF7jBex+jg4REo11XwNaRFerj5mP49z36eN6GT+snagJqUKuLfXTagzkB5iqRWPov0t3NUeU71YfYs6v/5sBkeMo0L1u86a3XfuvIvRe0Oc/RlXkCjBF8Yk9GrE1qvc3tZjp2dSaLBz+wmz8jJ7arpogbg72vXL46pmORKaFWyqfWh4OfrDoR1atC3jXnYtG1WjtitfW7AAreaaxEdweGpyb6A+iXcAYkgUunplUig31rPf9jVUlP42q/xmuG83YpgcZFg4ggfspkFHcfVoyGto8D9K2GjSi+9iJzhCf89rYioRJVEgJ0edPHiRi/IHrT+a6+4TVKwSJKm9dyEgZwW1zCzo7Rf7+M6Q5yr2k="
  client:
    serviceUrl:
      defaultZone: http://${eureka.username}:${eureka.password}@localhost:8761/eureka

encrypt:
  key-store:
    location: classpath:keystore.jks
    password: password
    alias: brewery

